### ISSUE TITLE
Simboluri alerte coloana tabel - problema tab reports

### ISSUE THREAD

**Issue by Horhellito** [porkmarks/sense#101]
Am vorbit aseara ca erau niste bug-uri ref simbolurile de alertare din tabelul tab-ului sensors.

Se pare ca au ramas aceste probleme in tabelul din Reports 

![image](https://user-images.githubusercontent.com/27699424/52177896-31946380-27d0-11e9-8023-6b9458517c63.png)

**Comment by jeanleflambeur** [comment]
1.0.16
