### ISSUE TITLE
Export Graph to PNG - Legenda se suprapune peste axa Y din dreapta...vezi atasament

### ISSUE THREAD

**Issue by Horhellito** [porkmarks/sense#102]
Export Graph to PNG - Legenda se suprapune peste axa Y din dreapta...vezi atasament

![1](https://user-images.githubusercontent.com/27699424/52177926-c008e500-27d0-11e9-8025-f20a75e8d8dd.png)

**Comment by jeanleflambeur** [comment]
Fixed 1.0.16
