### ISSUE TITLE
Alerta recurenta daca problema nu a fost rezolvata...discutie

### ISSUE THREAD

**Issue by Horhellito** [porkmarks/sense#103]
Asta e mai mult pentru mine sa imi amintesc sa te intreb. 

Daca o alerta apare la momentul actual (sa zicem temperatura sub nivel presetat) si ea ramane valabila o saptamana intreaga fara revenire, vine UN email de alerta doar cand a fost triggered alarma si apoi, daca isi revine vine mail de Recovered from...corect?

Ma gandesc (si poate povestim de asta) ca daca e asa cum am inteles, ar fi o idee ca daca alerta nu si-a revenit la un numar configurabil de ore (gen 12, 24, etc de ore), sa mai trimitem o alerta de reminder gen : alerta aia e inca activa (asa cum am vazut ca ai exprimat-o tu in body email STILL TRIGGERED) ca sa il forteze pe om sa o rezolve ... ca alminteri e posibil sa o lase asa si sa uite....(repet, daca nu se recoveruieste intr-un timp de...)

Vorbim!

**Comment by jeanleflambeur** [comment]
Suna a o idee buna, si e relativ usor de facut

**Comment by jeanleflambeur** [comment]
1.0.16
Trebe sa discutam despre format, sunt mai multe optiuni

**Comment by Horhellito** [comment]
ok! daca imi zici care-s optiunile, based on ce stiu ca vor astia....iti zic care cred ca e mai buna...
