### ISSUE TITLE
User Admin

### ISSUE THREAD

**Issue by Horhellito** [porkmarks/sense#106]
M-am gandit asa : In situatia in care am nevoie sa accesez setari dedicate strict pentru administrare cum ar fi : 
- modificare masuratori
- calibrare manuala senzori
- setare procent warning baterie
si altele
in loc sa dau sign out din userul curent si sign in as admin si apoi cand termin, sa dau iar sign out as admin si sign in as regular user...
ar fi mai bine ca atunci cand accesez meniurile respective sa ma prompteze cu un meniu in care sa invoc temporar drepturi de admin...
cu un singur amendament...daca modific inregistrarile de temperatura si umiditate din interfata, that should be like a secret feature, because it raises some moral/legal issues

mai discutam diseara

**Comment by jeanleflambeur** [comment]
Deja e asa.

**Comment by Horhellito** [comment]
![image](https://user-images.githubusercontent.com/27699424/71895654-4c96f280-315a-11ea-9e2c-bbf021ecbbaa.png)
Cand sunt logat cu userul creat de mine (farmacist) care are drepturile de mai jos, aparent poate sa schimbe comms periods (ceea ce nu vreau sa poata)
![image](https://user-images.githubusercontent.com/27699424/71895705-73552900-315a-11ea-8589-b1f8a11848e1.png)

**Comment by jeanleflambeur** [comment]
O lasasem asa intended. 
O sa adaug prop noua de Change Sensor Settings

**Comment by jeanleflambeur** [comment]
1.0.17
