### ISSUE TITLE
Export Reports to csv

### ISSUE THREAD

**Issue by Horhellito** [porkmarks/sense#108]
Cand apas pe Export, sa scot un raport pe un filtru facut, ar fi bine sa :
1. Imi sugereze un nume de raport default (cum ar fi "Report_data_inceput-data_sfarsit")
2. Sa avem un folder care sa se creeze automat la instalare, asemenea celui incercuit de mine, unde sa se pastreze user created reports BY DEFAULT.
![image](https://user-images.githubusercontent.com/27699424/71891186-b7dac780-314e-11ea-8d6d-71632fca973a.png)

**Comment by Horhellito** [comment]
3. In raport csv, la unitati, pentru grade Celsius apare un extra caracter
4. La unitatile de umiditate, in loc de % trebuie sa avem %RH.

![image](https://user-images.githubusercontent.com/27699424/71891654-bf4ea080-314f-11ea-984a-9cb0422b0105.png)

**Comment by Horhellito** [comment]
5. Pe grafic (atat in interfata cat si in graficul exportat, trebuie sa avem %RH in loc de % la umiditate, oriunde se mentioneaza umiditatea!

**Comment by jeanleflambeur** [comment]
1.0.17
