### ISSUE TITLE
Grafic - probleme cu annotations

### ISSUE THREAD

**Issue by Horhellito** [porkmarks/sense#109]
So:
1. Generez un grafic
2. Adaug annotations persistente
3. Schimb perioada (interval) filtru date/grafic
4. Graficul arata asa :
![image](https://user-images.githubusercontent.com/27699424/71892363-654eda80-3151-11ea-9dcc-df23666e93ea.png)

**Comment by Horhellito** [comment]
Probabil ca in cazul in care schimbam datele problemei (intervalul pe care facem raport/grafic) ar trebui sa se "CLEAR ANNOTATIONS" automat, pentru ca altfel se duc sagetile in ... afara monitorului =)))))))

**Comment by jeanleflambeur** [comment]
O sa fac ca daca masuratorile respective ies din cadru sa dispara annotatia.
Asta o sa rezolve si problema de mai sus, dar si situatia in care ai setat Today de exemplu si faci annotatii: in caazul asta pe masura ce apar masuratori, totul se va muta la stanga pana iese din ecran.

**Comment by jeanleflambeur** [comment]
1.0.17
