### ISSUE TITLE
Comms problems la un senzor

### ISSUE THREAD

**Issue by Horhellito** [porkmarks/sense#110]
![image](https://user-images.githubusercontent.com/27699424/71897362-0b551180-315f-11ea-8486-5608de737ad6.png)

**Comment by Horhellito** [comment]
Nu s-a intamplat nimic deosebit, senzorii sunt in acelasi loc toti, de aseara, calculatorul este pornit si aplicatia la fel, de aseara.

**Comment by jeanleflambeur** [comment]
Scoate pls al 2-lea base station din priza, se calca in picioare cu asta care e configurat.

**Comment by Horhellito** [comment]
Problema e ca nu stiu pe care sa il scot :))))
![image](https://user-images.githubusercontent.com/27699424/71904260-7ce88c00-316e-11ea-9d6a-a90ce8e34553.png)
Se calca in picioare chiar daca nu e "added" ????

**Comment by Horhellito** [comment]
Also, isn't that like a major issue? Pentru cand vom avea 2 base stations?

**Comment by Horhellito** [comment]
Update : Nu am oprit nici un BS pana la urma si acum vad ca si-a revenit. Doar am deschis rack-ul si le-am miscat putin sa vad daca pot sa identific care este cea neactiva...

**Comment by jeanleflambeur** [comment]
Da, se calca, ca BS-ul neadaugat aude ce zice senzorul si ii raspunde cu 'nu stiu cine esti'.
Scoate unul, asteapta 10-20 de secunde si daca e ala bun, baga-l la loc si scoate-l pe celalalt.

**Comment by jeanleflambeur** [comment]
In starea curenta, da, va fi o problema.
Fixul e: cand sunt BS-urile adaugate, vor vorbi intre ele si doar unul va raspunde.
Cand un BS nu e adaugat nicaieri, nu va raspunde nici unui senzur.

**Comment by Horhellito** [comment]
Imi amintesc ca au functionat in paralel mult timp fara probleme, cu 4 senzori asignati uneia si 4 senzori (altii) asignati alteia.

**Comment by jeanleflambeur** [comment]
1.0.17

**Comment by Horhellito** [comment]
Am reusit sa identific si sa Power Off base station-ul care nu era folosit.

It's still happening, acum cu 2 senzori: 

![image](https://user-images.githubusercontent.com/27699424/71938790-3d935d00-31b9-11ea-84d1-0f6e4bfe26e3.png)

**Comment by jeanleflambeur** [comment]
Ceva particular la senzorii aia? Antene/baterie diferite? Baga si screenshot cu sensor details pls.

**Comment by Horhellito** [comment]
![image](https://user-images.githubusercontent.com/27699424/71939118-54867f00-31ba-11ea-8bf9-a65e9b0c75bc.png)

**Comment by Horhellito** [comment]
Home3 are antena de la Newsteo. Dar si Home2 are antena de la Newsteo, si nu zice nimic.

C2 pe de alta parte are antena din cele cumparate de mine, care-s foarte ok. Antena de la C2 e identica cu antenele de la C1, C3, C4.

Bateriile sunt toate duracell, toate noi, desigur unele au ceva issues de long shelf life, dar sunt identice, din acelasi pack.

**Comment by Horhellito** [comment]
![image](https://user-images.githubusercontent.com/27699424/72025682-94646980-3281-11ea-9a03-33b986a0c7a2.png)
Se pare ca seara se intampla ceva

**Comment by Horhellito** [comment]
![image](https://user-images.githubusercontent.com/27699424/72025710-a6dea300-3281-11ea-9c49-eb07881aef9a.png)

**Comment by Horhellito** [comment]
Acum sunt toti pe 10 db, nimic nu s-a schimbat in afara de asta fata de ce era pana acum.
Newsteo sunt la fel, tot in aceleasi pozitii, tot transmitand ... ca si ieri.
Sidenote : Am urmarit Newsteo azi toata ziua, au transmis ALL OK, nu au avut interferente si probleme de la ai nostri....
Also, m-am uitat la Newsteo, sunt default pe high : 10 db

**Comment by Horhellito** [comment]
Si inca una de dimineata : 
![image](https://user-images.githubusercontent.com/27699424/72055225-1d57c100-32d3-11ea-9a6d-9295377c0d5e.png)

**Comment by Horhellito** [comment]
And about 30 min mai tarziu, alti 2 simultan
![image](https://user-images.githubusercontent.com/27699424/72057507-32365380-32d7-11ea-99ed-d20ec9c34224.png)

**Comment by Horhellito** [comment]
Again 
![image](https://user-images.githubusercontent.com/27699424/72102435-abfa2b80-332f-11ea-871c-5f8a3bb7f306.png)

**Comment by jeanleflambeur** [comment]
Am mai gasit o posibila cauza, un timeout care era prea la limita. 1.0.17
