### ISSUE TITLE
Email de alerta

### ISSUE THREAD

**Issue by Horhellito** [porkmarks/sense#111]
La umiditate, trebuie schimbata unitatea de masura din grade celsius in %RH.
La Battery Threshholds : Pune pls OK-ul verde dupa 20, pentru ca peste 20 baterie e ok
La Signal Strength Threshold, OK-ul tot DUPA 10, nu inaintea lui.

Danke :)

Check capture below 

<img width="641" alt="Screenshot 2020-01-12 at 21 24 33" src="https://user-images.githubusercontent.com/27699424/72224332-2326fe00-3582-11ea-815b-dc93243eb660.png">

**Comment by jeanleflambeur** [comment]
1.0.17
