### ISSUE TITLE
Dimensiune caption grafic

### ISSUE THREAD

**Issue by Horhellito** [porkmarks/sense#113]
Deodata :) s-au facut mai mari 
E vorba de cele 2 C3-uri unul din mijloc si celalalt din dreapta, ambele puse chiar acum. Celelalte erau puse ieri si au ramas acolo!
![image](https://user-images.githubusercontent.com/27699424/72903213-8577bf80-3d35-11ea-8af0-c3e6b133e10b.png)

**Comment by jeanleflambeur** [comment]
Asta nu ar trebui sa se intample in conditii normale. E din cauza ca m-am conectat eu cu TV cand era pornit si am 4k rezolutie. Pare bug de UI fie de la framework-ul pe care il folosesc fie de windows.
