### ISSUE TITLE
Password field shows password

### ISSUE THREAD

**Issue by jeanleflambeur** [porkmarks/sense#116]

**Comment by jeanleflambeur** [comment]
Cannot repro. 
Ti se mai intampla si in alte applicatii?
In versiunea 1.0.16 se intampla?

**Comment by Horhellito** [comment]
Se intampla si 1.0.16, dar DOAR la email!
Atat in 1.0.16 cat si un 1.0.17 se intampla la email.
Insa de exemplu la **adaugare de user nou**, NU SE INTAMPLA in nici una din versiuni.

La email dupa cum ai vazut, cand ma apuc sa scriu parola apar caracterele vizibile si abia cand ma mut in urmatoarea casuta, devin "stelute".

La adaugare user nou, comportamentul e normal, apar stelute de cand introduc parola noua si continua sa fie stelute cand confirm parola noua!

**Comment by jeanleflambeur** [comment]
1.0.18
Gata, reproduced. Asa a fost de ceva timp se pare, era configurat campul gresit.
