### ISSUE TITLE
App crash cand am apasat pe tab-ul graphs (la fel ca crash-ul de la legenda)

### ISSUE THREAD

**Issue by Horhellito** [porkmarks/sense#119]
Ideea e ca nu stiu exact daca era crapata si la "click" a disparut sau a fost generat evenimentul de click-ul meu pe tab-ul graph.

De asemenea nu sunt sigur ca nu ar fi crapat daca as fi dat click pe un alt tab din aplicatie...
[crash.txt](https://github.com/porkmarks/sense/files/4180357/crash.txt)

Sper sa fi uploadat fisierul care trebuie!

**Comment by jeanleflambeur** [comment]
1.0.19
