### ISSUE TITLE
Shutting down the app

### ISSUE THREAD

**Issue by Horhellito** [porkmarks/sense#122]
Idee : Totul a pornit de la faptul ca daca opresc aplicatia, nu primesc alerta de tip "bs disconnected" pe email. In schimb am observat ca aceasta alerta impreuna cu cea de tip "bs reconnected" vin impreuna la repornirea aplicatiei. 

So, is it possible ca la momentul in care dam "exit app" sau apasam pe x sa o inchidem, sa intre aplicatia intr-o mini procedura de shutdown care sa trimita mail cu "bs disconnected" si apoi sa se inchida?

Am observat ca la aplicatia Newsteo, cand o inchizi, are un progress bar la inchidere (sau ... un regres bar :))) ) in care spune "CLOSING SERVICES" sau ceva si apoi se opreste, dar in acel timp trimite si email ca s-a deconectat ....

How about it?

Danke schon

**Comment by jeanleflambeur** [comment]
1.0.19
