### ISSUE TITLE
Missing records la unul din senzori (birou)

### ISSUE THREAD

**Issue by Horhellito** [porkmarks/sense#16]
Dupa problema cu toate datele lipsa peste noapte al carui motiv l-am descoperit, azi, pe la 17, am verificat inregistrarile sa vad ce temperaturi si umiditati mai avem.

Toti senzorii ok, exceptand senzorul **BIROU** care nu a mai inregistrat de la 11 si ceva (sau nu a mai comunicat cu aplicatia de atunci)

Filmul explicativ pe email, se numeste "**18.10.2017 - reports - missing records for senzor Birou dupa ora 11siceva am.mov**"
[18.10.2017 - reports - missing records for senzor Birou dupa ora 11siceva am.zip](https://github.com/porkmarks/sense/files/1395124/18.10.2017.-.reports.-.missing.records.for.senzor.Birou.dupa.ora.11siceva.am.zip)

**Comment by Horhellito** [comment]
Incep sa cred ca e o problema de a transmite date catre BD cu senzorul "BIROU" pentru ca : 
- inregistrarile care lipseau ieri (de pe la 11am la 17) au aparut intre timp (ieri 18.10.2017)
- azi (19.10.2017) am verificat din nou toti senzorii pe filtru TODAY si toti in afara de "BIROU" au inregistrarile transmise corect in baza de date, ultima transmisie fiind cu mai putin de 10 minute inainte de ora curenta.
- senzorul "BIROU" insa, (de azi) are ultima inregistrare la 9:52 am, acum ora fiind 10:40am
(desigur am dat refresh la filtru)

Deci cred ca el inregistreaza (din moment ce gap-ul de records de ieri a aparut pana la urma, nu stiu cand si cum), dar nu transmite cfm specificatiei de 10 minute transmission.

Acum mai fac un test, voi opri aplicatia si o voi reporni sa vedem daca imi apar recordurile ........ si.... NU APAR :)

**Comment by Horhellito** [comment]
Dupa modificarea pozitiei antenei base station-ului, problema nu s-a rezolvat pentru senzorul Birou.

Acum e 11:37, iar ultimul record de la senzorul birou este 11:02 *desigur am refreshuit filtrul si desigur am verificat si ceilalti senzori si transmit ok.

Acum o sa iau senzorul si o sa il pun langa senzorul numit CABANA (care e mai aproape de base station si merge ok).

**Comment by Horhellito** [comment]
In secunda in care l-am pus langa celalalt, am vazut ca a blinkuit led-ul si a transmis datele (vizibile imediat in sistem). Il mai las aici cateva ore si apoi il mut inapoi in pozitia initiala sa vedem daca se reproduce problema.

**Comment by Horhellito** [comment]
In continuare senzorul problema (BIROU) este langa senzorul CABANA. L-am urmarit de atunci, si a mai fost o instanta in care nu a trimis inregistrarile la timp (la 10 min). De atunci insa nu am putut sta cu ochii pe el, dar vad ca trimite ok.

Peste cateva ore il mut inapoi sa vedem daca mai reproduce problema in pozitia veche.

Deci ceva ceva mai are, dar sigur nu mai are pauzele enorme dinainte. E posibil oare sa fie ceva problema cu antena de la router. Iti desenez o schema sa imi spui daca are sens.
![19 10 2017 - signal strength - amplasament senzor birou care nu transmite ocazional schita_final](https://user-images.githubusercontent.com/27699424/31770932-c111663c-b4e2-11e7-9bb0-13cbf9c89935.jpg)

**Comment by Horhellito** [comment]
Inca un senzor, cel de la Radu din camera, nemiscat de la inceput, nu a mai trimis date de o zi si ceva.
Cum l-am adus in birou, langa ceilalti, a inceput sa trimita din date (se vede in video).
Senzorul nu a fost miscat de cand i-am setat (pe 17 oct) iar BS l-am miscat o singura data atunci cand mi-ai zis sa pun antena in sus, dar de atunci au trecut 3 zile si senzorul de la Radu a transmis ok.

[23.10.2017 - SIGNAL STRENGTH - amplasament senzor radu nemiscat de 6 zile aseara nu a mai transmis.zip](https://github.com/porkmarks/sense/files/1408151/23.10.2017.-.SIGNAL.STRENGTH.-.amplasament.senzor.radu.nemiscat.de.6.zile.aseara.nu.a.mai.transmis.zip)

**Comment by jeanleflambeur** [comment]
fixed in 1.0.5
