### ISSUE TITLE
Auto Reporting

### ISSUE THREAD

**Issue by Horhellito** [porkmarks/sense#19]
In "Settings" / "Reports", Butonul "Send report now" merge din cand in cand :)
Nu am reusit sa reproduc nimic consistent.

Am definit o new ieri, am intrat pe ea si am dat send report now, nu merge....
Am definit o alarma noua acum, am apasat send report now si a mers apasat o data

**Comment by Horhellito** [comment]
Tot referitor la Auto Reporting, modul in care vin rapoartele (fie zilnice, saptamanale sau lunare) in mail, este o problema. Ar trebui sa ajunga sub forma de atasament CSV.

De asemenea, cand aleg "Summary Data" nu mi-e clar ce primesc.


Sensor | Min Temperature | Max Temperature | Min Humidity | Max Humidity | Alerts
-- | -- | -- | -- | -- | --
Birou 4FB | 24.5 °C | 29.5 °C | 37.6 %RH | 45.5 %RH | yes
Radu 992 | 23.5 °C | 29.0 °C | 38.4 %RH | 60.4 %RH | yes
Leea C44 | 23.4 °C | 28.5 °C | 40.0 %RH | 53.3 %RH | yes
Cabana EC2 | 16.7 °C | 29.7 °C | 40.0 %RH | 65.9 %RH | yes

Ce reprezinta astea? Ultimele inregistrari din fereastra "Sensors" ???

**Comment by jeanleflambeur** [comment]
Tabelul reprezinta min/max pentru temperatura si umiditate pe perioada selectata.
Daca ai raport pe zi, atunci vei avea minimele si maximele pt ziua respectiva, per senzor.

**Comment by Horhellito** [comment]
Pai nu e bine! Ideea este ca ei ar trebui sa primeasca un mail cu raport atasat in format CSV, Nu numai min/max pe perioada respectiva.

Pasii trebuie sa fie asa : 
1. In zona unde se configureaza "autoreporting" trebuie sa pot spune (la fiecare raport nou automat) de la ce senzor vreau sa primesc datele (asta se poate face acum).
2. Datele se ataseaza la un email informat ales de mine (ce se poate acum, cel mai bine csv, sau daca se poate in viitor PDF ar fi bine).
3. Raportul vine pe mail cu un subiect clar (raport / perioada) si cu un text gen "Please find attached the automatic report for the *period" si atasament. Fisierul trebuie sa fie exact ca ala exportat de mine cand fac un raport de mana.

**Comment by jeanleflambeur** [comment]
Raportul sumar e... sumar.
Daca alegi full report, primesti toate datele embedded in mail, nu doar sumarul.
Le-am facut html ca se pot converti usor in PDF prin printare. 

Pt CSV o sa mai dureze un pic pt ca trebuie sa fac configurarea de format embedded in raport.

**Comment by Horhellito** [comment]
Nu e o problema sa mai dureze. As vrea sa mai discutam un pic pe tema asta cu raportul full....Eventual pe facetime cu un teamviewer, ca nu cred ca e clar ce zic.

Danke :)

**Comment by jeanleflambeur** [comment]
All Data HTML sa fie ca atasament.
+ CSV format ca atasament

**Comment by jeanleflambeur** [comment]
Done: 1.0.17
Atasament CSV
Email body: min-max overview pentru perioada respectiva pentru senzorii selectati
