### ISSUE TITLE
Proces deploy

### ISSUE THREAD

**Issue by Horhellito** [porkmarks/sense#2]
1. Configurez si pair senzorii de acasa
2. Trimit pachet 
3. Clientul poate porni senzorii dar in general ii pornesc si inregistreaza pe drum pana ajung la ei.
4. Remote Teamviwer 
5. Copy kit (bat si fisiere resurse)
- bat ruleaza script / soft care sa scan network si config basestation cu ip computer database server
- sgbd se instaleaza pe port unic (in cazul in care mai exista un mysql instalat)

**Comment by jeanleflambeur** [comment]
Done.
