### ISSUE TITLE
Sensors / Reports / Logs - keep width of columns after modification 

### ISSUE THREAD

**Issue by Horhellito** [porkmarks/sense#22]
Pentru aceste taburi ar fi in viitor nice to have daca am salva pozitia din griduri ... tabele. 
![20 10 2017 - sensors reports logs - keep width of columns](https://user-images.githubusercontent.com/27699424/31829547-3bb3cb08-b5c6-11e7-9c50-fd220cfe82d4.png)

**Comment by jeanleflambeur** [comment]
Cred ca no probmem. Trebe sa verific ce-mi permite list widget-ul
