### ISSUE TITLE
Manager.exe crash after some days of working

### ISSUE THREAD

**Issue by Horhellito** [porkmarks/sense#23]
Azi (22.10.2017), am unlocked computerul pe la 14:40. Am vazut mesajul cu "manager.exe has crashed"
Asa ca am intrat in event viewer (vezi poze din atasament) si am vazut ca a crapat in jur de ora 9.
El a rulat non stop de la ultimul update. Nu resetez computerul si nu ii dau shut down seara. 
Am verificat in event viewer si am gasit doua chestii (in atasament)

![22 10 2017 - manager - event 1005 crash din event viewer](https://user-images.githubusercontent.com/27699424/31861571-5fcb9d7c-b738-11e7-8a67-9a4e1e63b279.JPG)
![22 10 2017 - manager - event 1000 crash din event viewer](https://user-images.githubusercontent.com/27699424/31861572-5fe6b1fc-b738-11e7-87b8-1eb0c74fee6c.JPG)

**Comment by Horhellito** [comment]
Update. Am repornit manager.exe dupa crash, si nu am date de loc. Am intrat in Settings/BS si zice Active / Disconnected. E posibil sa fie de la ceva pana de curent pe care am avut-o dar pana de curent nu a fost azi la 9 (cand a crashuit manager.exe) A fost ieri candva dimineata (ieri = 21.10.2017)

**Comment by Horhellito** [comment]
Aici gasesti un film cu restart Manager.exe after crash, cu date lipsa, BS aparent deconectat, si o NOUA PROBLEMA LA FILTRU PE SENZORI. Dupa ce schimb filtrul Sensors sa am date doar de la un sensor pe Reports, nu mi se inchide fereastra la OK sau in anumite conditii la cancel.

[22.10.2017 - MANAGER - restart after crash, no data, BS disconnected, problem filter Sensors.zip](https://github.com/porkmarks/sense/files/1404860/22.10.2017.-.MANAGER.-.restart.after.crash.no.data.BS.disconnected.problem.filter.Sensors.zip)

**Comment by Horhellito** [comment]
Azi (23.10.2017) iar l-am gasit crapat, si cfm event viewer (care avea doar un eveniment de data asta) e crapat tot la ora 9:00, identic cu ieri.

Iaca eventul : 

![23 10 2017 - manager - event 1000 crash din event viewer a doua oara](https://user-images.githubusercontent.com/27699424/31883569-f3a3ca28-b7f2-11e7-84dc-581769d8ed63.JPG)

**Comment by Horhellito** [comment]
De data asta nu a mai fost pana de curent.
Ieri am inregistrarile dubioase (dupa ce am repornit BS si i-am dat ip fix din router).
Pt data 22.10.2017 : 
- Senzor Birou are inregistrari de la ora 0 la 18:37
- Senzor Radu are inregistrari de la ora 0 la 04:27 (foarte putine)
- Senzor Leea are inregistrari de la ora 0 la 23:57 (asta aparent le are pe toate)
- Senzor Cabana (acum amplasat langa senzor Birou) are inregistrari de la ora 0 la 23:57 (deci toate)

De asemenea nu am umblat la nimic, dupa ce mi-ai dat noul exe ieri, am fost plecat toata ziua, azi dimineata am gasit crashul.

[data.zip](https://github.com/porkmarks/sense/files/1406683/data.zip)

**Comment by jeanleflambeur** [comment]
Datele lipsa sunt sigur din cauza ca nu le-a transferat inca.
Crash-ul cred ca are legatura cu BS-ul care isi ia IP nou for some reason (pana de curent, router config)

**Comment by Horhellito** [comment]
Nu stiu daca e din cauza ip-ului, ca alaltaieri i-am dat ip fix din router! Iar ieri la 9:00 iar crapase! 

Azi 24 oct, acum am verificat, nu a mai crapat la 9:00am!

**Comment by Horhellito** [comment]
Iar datele intr-adevar au aparut, dar e ceva cu semnalul ca uneori transferul e unreliable! Chiar si in cazul in care un senzor a stat nemiscat si BS nemiscat, a mers zile intregi si brusc a inceput sa nu trimita de loc sau sa trimita cu pauze (adica nu la fiecare transmission! Vezi ultimul exemplu cu senzorul Radu!

**Comment by jeanleflambeur** [comment]
- Da, am gasit buba de transfer. E de setari RF pe sensors si BS. Ma joc cu setarile aici sa gasesc ceva long range si reliable.
- Am rezolvat si fereastra de sensors (sunt defapt mai multe ferestre stacked una peste alta, se intampla doar daca dai double click pe base station in settings de cateva ori)
- Si problema de conexiune cand se schimba ip-ul si cred ca si crash-ul

**Comment by Horhellito** [comment]
A aparut al 3lea crash, de data asta nu la ora 9am ci la 11:48. Vezi captura event viewer. Ca de obicei, manager.exe era pornit si computerul locked.
![24 10 2017 - manager - event 1000 crash din event viewer a 3a oara](https://user-images.githubusercontent.com/27699424/31939879-b009e6b2-b8c4-11e7-98cf-5ecf3dce593b.JPG)

**Comment by Horhellito** [comment]
N-am mai avut rabdare pentru ca nu a mai crapat. Ideea e ca e posibil sa nu mai fi intrat in powersaving drive-ul de retea unde este pus manager.exe. Am simulat crash-ul oprind NAS-ul (unde este pus manager.exe) si rezultatul a fost crash, cu aceleasi eventuri in EVENT VIEWER de Windows, (atasate aici). Cand poti, intra sa iei si crashlog-ul din aplicatie.
![crash event viewer event 1000](https://user-images.githubusercontent.com/27699424/32277466-388d560c-bf1b-11e7-9f97-ca20f4238b95.png)
![crash event viewer event 1005](https://user-images.githubusercontent.com/27699424/32277467-38aa5ef0-bf1b-11e7-9fd8-59be1c13af3e.png)
![crash power off nas unde este instalat exe](https://user-images.githubusercontent.com/27699424/32277468-38c9b444-bf1b-11e7-88e9-2b19ae91c496.png)

**Comment by Horhellito** [comment]
[crash.txt](https://github.com/porkmarks/sense/files/1438849/crash.txt)

**Comment by Horhellito** [comment]
Crash varianta noua. Acum pare ca a crapat pe la ora 2AM cand am restartat eu routerul. Restartul a fost din web interface-ul routerului, nu prin scos si bagat cablu de alimentare.
Am atasat captura cu fereastra cu info...
![09 11 2017 - crash manager_exe - la restart router](https://user-images.githubusercontent.com/27699424/32603120-3d09b874-c551-11e7-8223-11db9d7a99e2.png)

**Comment by jeanleflambeur** [comment]
Fixed in V1.0.6
