### ISSUE TITLE
Reports/Select Sensors - Add Select All checkbox

### ISSUE THREAD

**Issue by Horhellito** [porkmarks/sense#24]
In Reports, la filtrul select sensors, adauga pls "Select All" (explicat in atasament)
![24 10 2017 - reports select sensors filter - add select all option](https://user-images.githubusercontent.com/27699424/31931869-357a8d3c-b8ad-11e7-9e89-d71c81b8a7a2.png)

**Comment by jeanleflambeur** [comment]
No problem. O sa adaug si Unselect all, nu?

**Comment by jeanleflambeur** [comment]
Nu e nevoie de Unselect All / Select None

**Comment by Horhellito** [comment]
That's very funny :)
