### ISSUE TITLE
Reports - daca sunt pe filtrul today - ziua curenta si trec de 12 noaptea, nu se schimba filtrul today in noua zi

### ISSUE THREAD

**Issue by Horhellito** [porkmarks/sense#25]
In tab-ul REPORTS, daca sunt pe filtrul TODAY, si trec de 12 noaptea, nu se updateaza filtrul pentru noua zi.

**Comment by jeanleflambeur** [comment]
No problem

**Comment by jeanleflambeur** [comment]
Fixed. O sa fie un delay de max 1 minut intre schimbarea de zi si actualizarea de filtru
