### ISSUE TITLE
Range issues

### ISSUE THREAD

**Issue by Horhellito** [porkmarks/sense#29]
So:

Test 1 : 3 days approx, senzori in cabana
Toti senzorii merg ok, fara probleme, baterie extensiv folosita la Leea (power 20)
Test 2 : comming up on 3 days, senzori la Mihai
La inceput, in prima zi, nu a mers niciunul. A doua zi am modificat pozitia BS-ului de la mine din birou dar modificarea a fost minora, in sensul ca am ridicat-o pe un raft mai sus, la 30 cm fata de unde era, insa pe orizontala pozitia nu s-a modificat. In acel moment am inceput sa vad DOAR SENZORUL LEEA, si pe ala il vad de aproape 2 zile incoace.
Senzorii amplasati la Mihai sunt unul langa altul, la o distanta de 5 cm unul fata de celalalt.

(distantele le vezi in pozele atasate)
![distanta_george_cabana 2](https://user-images.githubusercontent.com/27699424/33795856-ea191ffc-dcf1-11e7-99fd-c57e3e74e97d.png)
![distanta_george_mihai 1](https://user-images.githubusercontent.com/27699424/33795857-edcd695a-dcf1-11e7-9c77-e10d7ece7cfc.png)

**Comment by jeanleflambeur** [comment]
Antelene sunt shit. Am cumparat un device de masurat calitatea antenei si ce am eu in stock acum sunt super varza. Caut alt supplier sau o cale sa fac antene mai bune.

**Comment by Horhellito** [comment]
Vrei sa iti fotografiez modelul de la antenele de la Newsteo?

**Comment by Horhellito** [comment]
poze cu antena: 
![img_7637](https://user-images.githubusercontent.com/27699424/46665427-79adcb80-cbcc-11e8-84a8-d4a81acf893b.JPG)
![img_7642](https://user-images.githubusercontent.com/27699424/46665429-7adef880-cbcc-11e8-8b41-4902bb5c0629.JPG)
![img_7641](https://user-images.githubusercontent.com/27699424/46665431-7ca8bc00-cbcc-11e8-9967-17f4d35659e2.JPG)
![img_7640](https://user-images.githubusercontent.com/27699424/46665433-7dd9e900-cbcc-11e8-8c60-7a283b60559a.JPG)
![img_7638](https://user-images.githubusercontent.com/27699424/46665435-7f0b1600-cbcc-11e8-8024-0baf990ef391.JPG)

**Comment by Horhellito** [comment]
nope!
