### ISSUE TITLE
Communications fail not clear (related to "Range Issues")

### ISSUE THREAD

**Issue by Horhellito** [porkmarks/sense#30]
Atasez filmul (pe care il ai si pe whatsapp) cu toate explicatiile necesare.
[issue with sensor not showing that they are not communicating.zip](https://github.com/porkmarks/sense/files/1544694/issue.with.sensor.not.showing.that.they.are.not.communicating.zip)

**Comment by jeanleflambeur** [comment]
Fixed in 1.0.6
