### ISSUE TITLE
Admin status

### ISSUE THREAD

**Issue by Horhellito** [porkmarks/sense#40]
E normal sa nu pot adauga un nou user cu drepturi de administrare?
Nu mai tin minte daca am discutat ca ramane un singur admin sau pot fi mai multi.

Oricum, in caz ca e bug, cand adaug user nou, checkbox "Administrator" este inactive.

**Comment by jeanleflambeur** [comment]
Softul suporta orifati useri admin. La u nmoment dat mi-ai zis tu sa fie doar unul.
Pot da undo la schimbare

**Comment by Horhellito** [comment]
Asta e, ca uitasem de faza cu doar unul! Daca asa am zis, sigur am avut un motiv bun atunci :) asa ca lasa asa.
