### ISSUE TITLE
put sensors to sleep este inactiv (checkbox)

### ISSUE THREAD

**Issue by Horhellito** [porkmarks/sense#41]
In Settings->Sensors - put sensors to sleep este inactiv (checkbox)

**Comment by jeanleflambeur** [comment]
Not implemented for now.
Poti sa-mi descrii din nou cum ar trebui sa mearga pls?

**Comment by Horhellito** [comment]
La fel ca la sistemul Newsteo (senzorii negri cu antene vizibile) adica : 
1. Bifez "put sensors to sleep"
2. Apas pe un buton (in Newsteo este un send)
3. Senzorul intra in sleep (hibernate la newsteo) si poate fi trezit cu un magnet (sau in cazul nostru cu apasarea fizica a butonului de pe senzor

Scopul este battery saving daca senzorii nu sunt folositi pe termen mediu sau lung.

**Comment by jeanleflambeur** [comment]
1.0.10
