### ISSUE TITLE
Signal Strength

### ISSUE THREAD

**Issue by Horhellito** [porkmarks/sense#42]
Indicatorul Signal Strength imi arata la toti senzorii valori ciudate. Acum de exemplu valorile sunt intre 38 si 48% signal strength. Senzorii sunt la o distanta de 3-7 metri fata de base station in camere diferite.

Problema este : Clientul se sperie de rapoarte inaccurate la chestiile astea. De exemplu la Newsteo, raportarea bateriei este dodgy si inaccurate si extrem de variabila, iar pe noi avem 60% din apeluri pe tema sistemelor de monitorizare din cauza raportarii bateriei. 
In schimb la Newsteo, signal strength indicatorul are sens si este destul de accurate. Adica daca-s cu senzorii la 1 metru de receiver (base station de la newsteo), imi arata 100% si cumva pe masura ce ma indepartez incepe sa scada dar intr-un mod intuitiv.

Avem cum "calibra" indicatorul ala de signal strength? Adica sa devina mai intuitiv, chiar daca nu reprezinta realitatea neaparat, si sa dea warning doar daca e cutoff total?

**Comment by jeanleflambeur** [comment]
Asta e trick. Semnalul e slab la tine din cauza de interference cel mai probabil.
La mine imi arata 90-100% cand senzorii sunt aproape.
Pot face o remapare, ce-i acum 50% sa fie aratat ca 100%, 25% sa fie 50% samd.

**Comment by Horhellito** [comment]
E posibil sa fie asa. Pentru ca am gateway-ul acela care imi controleaza intrerupatoarele, dar ala nu emite constant, emite doar cand ii dau eu on off la un switch din telefon.
Senzorii de la Newsteo, pe ~800 nu fac fitzele astea la semnal. Adica langa receiver alea imi arata 100%.
Ramane deschisa chestia asta, o sa incerc sa elimin gateway-ul temporar (adica cel de intrerupatoare) sa vedem cum se comporta.
De asemenea o sa ii mut cu tot cu base station si in alta parte...
Iti zic cum evolueaza...

**Comment by Horhellito** [comment]
In faza 1 am oprit tot ce putea interfera cu senzorii, mai ales gateway-ul care merge pe ~433 (ala care controleaza luminile si apoi am scos tot si dezactivat si wireless.
In faza 2 am mutat base station cu tot cu senzori intr-o zona free of crap...acum nah...vecinii au wireless, dar totusi e 2.4.

Arata tot dubios semnalul, cu senzorii aproape de base station...vezi atasament:
![semnal after removing interference](https://user-images.githubusercontent.com/27699424/45317362-77f7d600-b542-11e8-8134-67047ef8e0d3.png)

**Comment by jeanleflambeur** [comment]
Vad ca signal strength difera si intre senzori. E foarte posibil sa fie antenele proaste, de aia au si fost probleme de semnal pa Mihai acasa. Am comandat un device intre timp sa tunez antenele si o sa facem un test cu versiunea urmatoare de device-uri.

**Comment by jeanleflambeur** [comment]
Range-ul e atat de random ca antenele sunt proaste. Caut alt supplier
