### ISSUE TITLE
Settings - Reports

### ISSUE THREAD

**Issue by Horhellito** [porkmarks/sense#43]
La Rapoarte (in Settings) cand definesc un nou raport, selectez ca vreau sa imi vina raportul doar de la un senzor (selectez senzorul pe care il vreau) si dau SEND REPORT NOW inainte de a da OK pentru a salva raportul, imi trimite mail INSA imi trimite raport pentru toti senzorii (eu selectand doar unul).

Sugestie : Disable butonul "send report now" cat timp creez (editez) raportul nou, si activeaza-l doar pe lista de rapoarte. Adica dupa ce am salvat raportul nou, presupunem ca am o lista de 3 rapoarte salvate.
Selectez raportul dorit, si apoi apas pe "send report now" si asa imi pot trimite orice raport din lista (cu criteriile clar definite) in momentul dorit de mine.

How about it?

**Comment by jeanleflambeur** [comment]
fixed in 1.0.7

**Comment by Horhellito** [comment]
Am observat ca si raportul in sine dupa ce il salvez doar pe un senzor imi vine de la toti senzorii.
Daily report: Leea

Sensor | Min Temperature | Max Temperature | Min Humidity | Max Humidity | Alerts
-- | -- | -- | -- | -- | --
Birou 4FB | 25.3 °C | 25.8 °C | 48.2 %RH | 48.6 %RH | no
Radu 992 | 26.9 °C | 27.2 °C | 48.2 %RH | 49.4 %RH | no
Leea C44 | 26.0 °C | 26.1 °C | 48.6 %RH | 48.6 %RH | no
Cabana EC2 | 24.5 °C | 25.3 °C | 54.9 %RH | 56.5 %RH | no
