### ISSUE TITLE
Graphs - reselect filter perioada

### ISSUE THREAD

**Issue by Horhellito** [porkmarks/sense#44]
Daca in Graphs sunt pe "Today" si am ramas pe "Today" de ieri, graficul nu mi se updateaza automat. Asta nu ar fi un issue, decat daca se poate face usor.

Insa, bug-ul este ca daca dau click pe combo si RESELECTEZ "Today" pentru a face refresh, nu se schimba nimic, nu face refresh. Trebuie sa selectez altceva (gen Yesterday sau orice) si apoi sa reselectez "Today" ca sa imi faca refresh. Asta e o problema de usage!

**Comment by jeanleflambeur** [comment]
Hmm, bug. Ar trebui sa-si faca refresh la Today automat.

**Comment by jeanleflambeur** [comment]
Nu pot sa repro. Poti sa mai incerci pls si sa-mi mai dai detalii?

**Comment by Horhellito** [comment]
Nu e foarte usor de reprodus! O sa incerc! Ideea e asa : 
1. Lasi softul pornit pe Graphs cu filtru TODAY.
2. Trece ziua 
3. A doua zi esti tot pe TODAY, dar graficul efectiv este cel de ieri pentru ca nu isi face refresh.
4. Dai click pe combo si selectezo TOT Today. 

At this point nothing happens, ramane pe acelasi filtru TODAY (de ieri) iar graficul nu isi face refresh

**Comment by jeanleflambeur** [comment]
Fixed 1.0.7

**Comment by jeanleflambeur** [comment]
Daca se mai intampla, fa pls un screenshot cu problema (inainte sa schimbi perioada, si back la Today).
Vreau sa vad ce date sunt in campurile de From si To.
