### ISSUE TITLE
Grafic - perioade cu date lipsa

### ISSUE THREAD

**Issue by Horhellito** [porkmarks/sense#46]
Pentru perioadele cu date lipsa, pe grafic in acest moment se face o legatura (printr-o linie) intre ultima valoare inregistrata la intrerupere si prima valoare inregistrata dupa o perioada de timp.

Ar trebui cumva evidentiat ca pe perioada respectiva, in mod CLAR lipsesc date. 
Ori prin hashurarea liniei ori prin eliminarea ei pe perioada de date lipsa.

Vezi atasament !
![grafic_evidentiere_date_lipsa](https://user-images.githubusercontent.com/27699424/45295841-bc668000-b508-11e8-9a27-62669da945cf.png)

**Comment by jeanleflambeur** [comment]
Fixed 1.0.7
