### ISSUE TITLE
Graph - Filtru "Today" cand s-a schimbat ziua

### ISSUE THREAD

**Issue by Horhellito** [porkmarks/sense#50]
Nu mai stiu daca mai deschisesem un issue pe tema asta, dar nu l-am gasit.
Mi-ai zis sa las pe "Graph" pe Today, pana se schimba ziua.
Am facut captura, vezi atasament 👍 
![captura_schimbare_zi_filtru_ramas_today](https://user-images.githubusercontent.com/27699424/45394115-c9ce5800-b637-11e8-883c-095c02190d2e.png)

**Comment by jeanleflambeur** [comment]
Fixed 1.0.8
