### ISSUE TITLE
Timp de masurare / timp de transmitere records

### ISSUE THREAD

**Issue by Horhellito** [porkmarks/sense#57]
Am modificat timpii (atat de transmitere cat si de masurare) la niste timpi foarte mici pentru ca vroiam multe record-uri repede pentru ceva. Pare ca nu merge setarea.

![image](https://user-images.githubusercontent.com/27699424/46639395-6409b900-cb6e-11e8-8705-ef90161099ae.png)

Iata ce apare in logs cand dau apply la schimbarile de timpi : 
![image](https://user-images.githubusercontent.com/27699424/46639412-8f8ca380-cb6e-11e8-9a5b-7e0e0be97087.png)

Also, inainte era 15 min Measurement Period si 15 min Comms Period iar la "actual comms period" era tot 15 min (cel ne editabil). De cand am schimbat la Measurement Period 0.5 min si Comms Period 1 min, mi s-a modificat "actual comms period" la 10 min for some strange reason...

**Comment by jeanleflambeur** [comment]
Verific acum.
Actual comms period iti arata perioada de comms calculata de BS in functie de diverse chestii, dar 10 min e prea mare.

Faza e ca fiecare senzor are alocat un slot de 10 secunde de comms. Pe langa asta mai sunt 10 secunde de silence intre senzuri, deci fiecare senzor are nevoie de 20 secunde total pt comms.
Daca ai 6 senzori, comms period nu are cum sa fie mai mic de 2 minute - si actual comms period iti va arata asta.

**Comment by jeanleflambeur** [comment]
1.0.9

**Comment by Horhellito** [comment]
OK! E clara problema cu "actual comms period" in sensul in care nu are cum sa fie mai mic de 2 minute, dar in cazul curent asa cum ai zis si tu, 10 minute e prea mare. Insa ramane problema cu setarea pe care am facut-o eu pentru measurement period (cea mai importanta) si cea cu comms period ... care nu sunt actually setate in senzori conform erorii din loguri.
