### ISSUE TITLE
Rebind existing sensors

### ISSUE THREAD

**Issue by jeanleflambeur** [porkmarks/sense#63]

**Comment by Horhellito** [comment]
what does this mean? :)

**Comment by jeanleflambeur** [comment]
Daca ai un senzor adaugat si se strica, vrei sa poti pune un senzor nou in locul lui.
Acum singura posibilitate e sa dai remove la senzorul vechi si sa adaugi senzorul nou. Problema e ca asta sterge toate masuratorile de la senzorul nou.

**Comment by Horhellito** [comment]
Noul senzor o sa aiba alta serie? O sa fie identificabil cumva ca a fost inlocuit senzorul de la data de / ora de? Pentru ca in farma exista o tona de proceduri si procese verbale cand se strica/inlocuieste un senzor...

**Comment by jeanleflambeur** [comment]
1.0.17
