### ISSUE TITLE
Leftover records in memoria senzorilor

### ISSUE THREAD

**Issue by Horhellito** [porkmarks/sense#67]
Manager.exe ruleaza de cand am vorbit pe Facetime. 
V1.0.10.
Uitandu-ma fugitiv pe interfata acum, am vazut ca toti senzorii au cateva (putine) date in memorie. 
N-am avut pana de curent, nu s-a intamplat nimic cu computerul pentru ca practic nu l-am atins de cand am vorbit noi pana acum...

![image](https://user-images.githubusercontent.com/27699424/46930407-22857c00-d04e-11e8-9871-407485587c64.png)

**Comment by jeanleflambeur** [comment]
Fixed 1.0.10
