### ISSUE TITLE
Discuss about battery levels - ce se afiseaza si cand warning...

### ISSUE THREAD

**Issue by Horhellito** [porkmarks/sense#69]

**Comment by jeanleflambeur** [comment]
Apropo de batt consumption so far.
Senzorul parasuta a scazut 14% (de la 49% la 35%) dupa 3817 masuratori. Daca am masura la 15 min asta ar insemna 39 de zile. 14% in 39 de zile rezulta in battery life de ~300 de zile ceea ce e cam putin intr-adevar (ar trebui sa fie dublu).
Pe de alta parte bateria nu se consuma liniar asa ca hai sa luam alt senzor.

Birou:
De la 54% la 44% (deci 10%) pt 4604 masuratori, adica echivalentul la 48 de zile. Deci extrapolat la 480 de zile full battery.

Remote:
De la 57% la 44% (deci 14%) pt 4604 masuratori. Adica un total extrapolat de 369 de zile.

Spring:
De la 51% la 42% (9%) pt 3849 masuratori. Adica ~400 zile extrapolate.

Uite o curba de descarcare de baterie tipica:
https://eu.mouser.com/datasheet/2/315/panasonic_lithium_cr2_cr123a-947444.pdf

E foarte nonliniara, adica dureaza mult intre 100% si 40-50% dupa care pica brusc.
Procentul curent arata cata capacitate mai are bateria in ea si e accurate (+/- 3-4%) dar nu e bun pt estimarea de timp pentru ca echivalenta timp<->capacitate nu e liniara.
O sa incerc sa caut info despre asta, poate sunt cai de estimare mai bune.

**Comment by Horhellito** [comment]
Inteleg!
Poate ca ar trebui sa fac testele astea din nou pe niste baterii noi! O sa comand cateva sa vedem! De asemenea o sa ma gandescu cum o sa modificam modul de afisare al bateriei astfel incat sa imi afiseze cumva in chunk-uri pentru ca nu e ok sa imi afiseze la senzor nou cu baterie noua un procent mai mic de 100%. (din cauza clientilor care nu inteleg, se leaga de asta si pierdem o gramada de timp sa le paraexplicam).

**Comment by jeanleflambeur** [comment]
Am refacut estimarea de baterie, ar trebui sa fie mai clara acum. Alerta la 10% (o putem schimba), si la signal si la baterie
1.0.16
