### ISSUE TITLE
Adaugare senzori noi, nu apar date si inregistrari de la acei senzori, nu se updateaza grafic. 

### ISSUE THREAD

**Issue by Horhellito** [porkmarks/sense#71]
Adaugare senzori noi, nu apar date si inregistrari de la acei senzori, nu se updateaza grafic. 
Stiu ca si ieri a fost o faza de genul asta si s-a rezolvat dupa restart. Deci e posibil sa fii deja aware of it.

Dau restart! Pana una alta, astia-s senzorii noi, si zona de Reports, fara nici o inreg de la ei... 

![image](https://user-images.githubusercontent.com/27699424/49441347-e4dfdc80-f7ce-11e8-84db-cb3485631a98.png)
(mai jos vezi ca sunt doar Birou si Remote, cei adaugati de ieri)

![image](https://user-images.githubusercontent.com/27699424/49441384-fa550680-f7ce-11e8-80f9-775ecd8375e5.png)

**Comment by jeanleflambeur** [comment]
1.0.13
