### ISSUE TITLE
Alert email highlight

### ISSUE THREAD

**Issue by Horhellito** [porkmarks/sense#74]
Cand primim o alerta pe email de forma : 
Sensor 'Spring' triggered alarm 'Spring'.
Measurement:
•	Temperature: 25.2 °C
•	Humidity: 28.6 %RH
•	Battery: 52 %
Timestamp: 04-12-2018 14:07 (dd-mm-yyyy hh:mm)

trebuie evidentiat cu rosu valoarea care este in alerta. Adica daca e doar temperatura in alerta, atunci 
* Temperature : 25.2 .... sa fie rosu bold 

daca e si temperatura si umiditatea, atunci ambele randuri cu rosu bold
daca e doar bateria, atunci doar bateria, etc etc

**Comment by jeanleflambeur** [comment]
1.0.12
