### ISSUE TITLE
email settings issue

### ISSUE THREAD

**Issue by Horhellito** [porkmarks/sense#76]
Sunt in punctul in care am vrut sa scot din configurarile de email adresele de mail configurate initial.
Din pacate nu pot sa le scot, decat daca dau reset ceea ce ce inseamna ca tre sa sterg si configurarile contului de email ca atare (SMTP, port, credentiale, etc).
Ar fi ok sa pot seta si salva configurarea contului de email dar sa imi permita si lista vida, cu eroarea captata si returnata ca mesaj gen : list is empty...cannot send email blah blah

**Comment by jeanleflambeur** [comment]
1.0.12
