### ISSUE TITLE
Show last measurement timestamp for each sensor

### ISSUE THREAD

**Issue by jeanleflambeur** [porkmarks/sense#8]

**Comment by jeanleflambeur** [comment]
Asta e mai complicat un pic, are nevoie de o schimbare de soft de base station. In momentul asta BS-ul nu trimite datele astea (next comms timestamp)

**Comment by jeanleflambeur** [comment]
@Horhellito

**Comment by Horhellito** [comment]
No problem...ramane deschisa pt cand poti.

**Comment by jeanleflambeur** [comment]
fixed in 1.0.5
