### ISSUE TITLE
Data Gap la toti senzorii

### ISSUE THREAD

**Issue by Horhellito** [porkmarks/sense#81]
O chestie pe care nu am observat-o la inceputul saptamanii pentru ca nu facusem filtru pe o perioada anterioara suficient de mare. Lipsesc date intre 5 Dec si 8 Dec. E probabil sa fi fost si software oprit, dar ideea era sa se transfere datele daca sistemul nu merge. Can you please check it out.

Thanks.

Vezi capturi mai jos...

![image](https://user-images.githubusercontent.com/27699424/49716526-acbc1c00-fc5c-11e8-9fe2-f72105991b69.png)
si
![missing data 1](https://user-images.githubusercontent.com/27699424/49716551-b5aced80-fc5c-11e8-8543-1e2027bbf519.png)

**Comment by jeanleflambeur** [comment]
Programul a fost oprit pe 5 si repornit pe 10.
La o perioada de masuratori de 1 minut senzorii pot stoca cam o zi maxim de date (super best case, more like 16-17h).
Ce e ciudat e ca gap-ul nu e mai mare. Cred ca avem o problema de logging.

**Comment by Horhellito** [comment]
Acum realizez ca de fapt sunt setati la 1 minut.... :) Sorry!
