### ISSUE TITLE
Crash cu oprire aplicatie

### ISSUE THREAD

**Issue by Horhellito** [porkmarks/sense#83]
Acum ca citeam tot ce ai scris tu si verificam unde era chestia cu tab order, am inceput sa dau clickuri pe taburile din settings, si initial aveau un lag mare (gen dadeam click pe tabul email (venind din tab-ul ftp de exemplu si statea unresponsive pt cateva secunde si apoi mergea). Dupa cateva momente de lag mare, pur si simplu s-a descarcat aplicatia din memorie la al 4-5-lea click pe taburi. Nu stiu daca se refera doar la tab-urile din settings.

Ca log, ora la care s-a intamplat a fost 12:41, 10 Dec 2018

**Comment by jeanleflambeur** [comment]
Fixed 1.0.14
