### ISSUE TITLE
INTREBARE : Calibrarea la senzori (temp sau umiditate) se salveaza in memoria senzorului ?

### ISSUE THREAD

**Issue by Horhellito** [porkmarks/sense#90]
INTREBARE : Calibrarea la senzori (temp sau umiditate) se salveaza in memoria senzorului ? Adica daca eu unpair-uiesc senzorul si il repair-uiesc ... sau ... daca il setez de acasa si apoi il livrez la client pe instalare de soft noua ... raman parametri de calibrare activi?

**Comment by jeanleflambeur** [comment]
Da, se salveaza in memoria senzorului, regardless la ce BS e legat.
