### ISSUE TITLE
Cand configurez "Reports" si ii dau send report now, imi zice ca nu e recipient configurat, desi este configurat in Settings->Email

### ISSUE THREAD

**Issue by Horhellito** [porkmarks/sense#91]
Cand configurez "Reports" si ii dau send report now, imi zice ca nu e recipient configurat, desi este configurat in Settings->Email

**Comment by jeanleflambeur** [comment]
fa-mi pls un zip cu folderul data si ataseaza-l aici.
Tocmai am testat cu pasii de la tine si merge. Trebuie sa fie altceva.

**Comment by Horhellito** [comment]
Pas 1. 
![image](https://user-images.githubusercontent.com/27699424/51387828-313d6c80-1b30-11e9-8fc4-d144c42e67dd.png)

Pas 2. (ma uit in Logs)
![image](https://user-images.githubusercontent.com/27699424/51387841-3c909800-1b30-11e9-8b8d-4dd39be95a1f.png)

Referinta la zona de email unde ESTE configurat recipient (si merge daca dau test email si ajunge mailul de test)
![image](https://user-images.githubusercontent.com/27699424/51387862-4fa36800-1b30-11e9-995b-2dce5475218c.png)

Folderul data in zip
[data.zip](https://github.com/porkmarks/sense/files/2772963/data.zip)

**Comment by jeanleflambeur** [comment]
Ok, got it.
Ce s-a intamplat e asa:
1. Aveai un recipient
2. Ai dat remove recipient
3. Ai dat Apply (din momentul asta sunt zero recipients)
4. Ai dat Add Recipient (deci in box-ul din settings apare un recipient - ala din screenshot)
5. NU ai dat Apply - deci recipient-ul e doar in UI dar nu si in system

Daca dai restart - va disparea recipient-ul din box
Daca dai apply - vei avea recipient si rapoartele vor merge.

Ma gandesc sa scot tab-ul de settings si sa-l pun ca si menu entry (Tools->Settings).
In felul asta nu ai cum sa lasi setari in mijlocul editarii: cand vrei sa iesi din settings inchizi fereastara de settings fie dand Ok fie Cancel.
Data viitoare cand deschizi Settings-urile, vezi din nou starea currenta a datelor, nu ce aveai tu mid-edited.

Cu alte cuvinte situatia de acum nu va mai avea cum sa se intample.

**Comment by Horhellito** [comment]
Nu schimba inca interfata, lasa-ma sa ma gandesc si eu putin! Pe de alta parte poate ca ar trebui sa nu ma lase sa plec din fereastra aia fara Apply! Gen un mesaj! Leave without applying changes? Sau Apply changes before exiting

**Comment by jeanleflambeur** [comment]
1.0.16
