### ISSUE TITLE
De la ce procent imi da alerta de Low Battery? (cand configurez alerta de low battery)

### ISSUE THREAD

**Issue by Horhellito** [porkmarks/sense#92]
De la ce procent imi da alerta de Low Battery? (cand configurez alerta de low battery)

**Comment by jeanleflambeur** [comment]
Shit, bug, Levelul de alerta e mai jos de 0%, adica alerta de low batt nu se trigereaza.
Fixed in 1.0.14

**Comment by jeanleflambeur** [comment]
Nivelul in 1.0.14 e 10%. Il pot pune cat vrei tu, pot sa-l fac si configurabil

**Comment by Horhellito** [comment]
Daca nu e super complicat si nu implica schimbari majore, ar fi ideal sa fie configurabil.
