### ISSUE TITLE
Email notifications do not work

### ISSUE THREAD

**Issue by Horhellito** [porkmarks/sense#93]
Nu merg notificarile pe email (alerte). Am setat cateva alerte specifice, sa testez cat mai multe scenarii.
Am verificat setarile de mail iar "TEST MAIL" merge, si primesc emailul.
Insa notificarile nu ajung de loc. E posibil sa fie related cu faptul ca la RAPOARTE, imi spune ca nu am recipient setat, desi am.

E posibil sa fie un bug de genul : 
1. Eu am adaugat setarile de cont de mail.
2. Am adaugat un singur recipient : george@metrocert.ro
3. Am sters recipientul - pentru a testa noul feature, adica faptul ca raman setarile de cont de mail chiar daca sterg recipientul ( a fost un change request anterior al meu )
4. Am readaugat acelasi recipient : george@metrocert.ro

Nu am testat inainte sa fac smecheria asta, deci e posibil sa fie ceva bug generat de pasii de mai sus, sau pasii de mai sus sa fie irelevant si sa nu mearga oricum.

**Comment by jeanleflambeur** [comment]
Nu ai dat apply dupa ce ai re-adaugat recipient-ul.
Vezi comment-ul de la bugun cu rapoartele  si "No Recipients"

**Comment by Horhellito** [comment]
Am raspuns acolo
