### ISSUE TITLE
Email ALARMS still a problem

### ISSUE THREAD

**Issue by Horhellito** [porkmarks/sense#95]
Hola,

Am vazut ca ai pus noua versiune si ai pornit-o pe laptopul unde ai fost conectat. 
Am oprit-o de acolo si am pornit-o pe laptopul meu.
Am intrat la email config UNDE NU ERA RECIPIENT configurat ci doar cont
Am adaugat recipient si in continuare se intampla ce s-a intamplat si pana acum, respectiv : 

![image](https://user-images.githubusercontent.com/27699424/51845988-63658000-2321-11e9-8bba-68cd722248b2.png)

Adica daca adaug un recipient in timp ce merge manager.exe, imi trimite test mail, dar nu si alertele...si posibil nici rapoartele automate...
Acum am restartat aplicatia sa vedem daca merge INSA e o problema pentru ca daca sa zicem ca se adauga un recipient nou la lista in timp ce programul ruleaza, ala nu primeste nimic pana la eventual restart (acum ramane de vazut daca merge dupa restart manager.exe - will get back to you on that one)

**Comment by Horhellito** [comment]
Dupa restart tot nu se trimit
![image](https://user-images.githubusercontent.com/27699424/51858773-307db500-233e-11e9-8174-70bbdb308291.png)

**Comment by Horhellito** [comment]
Am restartat de cateva ori, am adaugat, uneori s-a salvat adresa de mail (desigur am dat apply) dar ceva nu este in regula acolo...acum de exemplu am adaugat mail, restartat si merg alertele...

**Comment by Horhellito** [comment]
Dupa cateva ore de functionare, de cand am scris ieri (nu stiu exact cand s-a oprit) - se vede in captura - am incercuit zona in care brusc nu au mai mers (fara pana de curent, fara reset computer, fara restart manager.exe....)
[data.zip](https://github.com/porkmarks/sense/files/2812027/data.zip)

![moment in care nu mai merg mailurile](https://user-images.githubusercontent.com/27699424/51973787-1dc2c780-2487-11e9-8d1b-847eceada168.png)

**Comment by Horhellito** [comment]
Mi-a venit idea sa verific daca merge "TEST" la configurarea emailului in manager.exe si guess what :) Nu mai merge...
![image](https://user-images.githubusercontent.com/27699424/51975636-6bd9ca00-248b-11e9-9c03-a2476617e68c.png)

**Comment by jeanleflambeur** [comment]
Asta pare sa fie un timeout sau ceva de la engine-ul de email.
Time iti merge net-ul, emailul etc?
Poti verifica daca email notif iti merg din celalalt program (de la ceilalti senzori)?

**Comment by jeanleflambeur** [comment]
Legat de prima chestie, ce zici e ca adaugi recipient, dai apply (esti 1000% sigur) si tot primesti eroare de no recipient configured?
Cand ti se intampla asta (eroarea de no recipient), fa asta pls:
1. Fa un zip cu datele pt mine
2. Restarteaza program-ul  si verifica dupa aia in settings data chiar ai recipient configurat (dupa restart).

**Comment by Horhellito** [comment]
Pe rand : 
In primul rand ti-am atasat deja data.zip, este mai sus. M-am cam obisnuit sa fac asta default...e posibil sa il fi ratat ca e mic :) 

- imi merge net si email si tot...verificat de atunci....
- din celalalt program merg notificarile pe mail
fac alt issue daca insisti dar cred ca e related, pentru ca initial test mail mergea si nu se trimiteau mailurile de alerta, dar acum coincide momentul in care nu mai merge test mail cu erorile de trimitere mail alerte (care au mers o perioada fara probleme asa cum se vede din captura aia in care am incercuit)

**Comment by jeanleflambeur** [comment]
Sunt probleme total diferite, hai sa nu le amestecam.
Prima - cu no recipient, e ceva de la noi. Fie de UI fie de salvat de date.
A 2-a e eroare de trimis mail: **550 5.4.5 Daily user sending quota exceeded.**
Se pare ca contul tau are quota de mails si l-am depasit.

**Comment by Horhellito** [comment]
contul meu de mail recipient?
nici nu am vazut...
raman la idea sa putem configura cate mailuri se trimit si de cate ori per alerta activa...

**Comment by jeanleflambeur** [comment]
Contul monitorizaremtc@gmail.com are o limita de send impusa de google pe care noi o triggeram. De aia dadea Client Error.
Nu are treaba cu recipients, e problema de smtp si limite de google.

Nu ar trebui sa se mai intample acum ca am reparat un bug care cauza email de alerta la fiecare masuratoare, deci rata de mailuri va scadea drastic.
Cu toate astea - s-ar putea intampla in cazuri reale daca fluctueaza un senzor si trigereaza alera on/off la fiecare masuratoare.
Cel mai bine ar fi sa contactezi un serviciu de smtp pe bani, cu limite decente. Gmail nu e facut pt asta - mai ales ca tu share-uiesti contul asta pt toate sistemele de monitorizare.

**"raman la idea sa putem configura cate mailuri se trimit si de cate ori per alerta activa..."**
La ce te referi?

**Comment by Horhellito** [comment]
Eu contractez un smtp pe bani fara probleme dar clientii nu vor face asta!
The whole point (as opposed to sms) e ca au notificari instante gratis!

Folosesc acelasi cont de gmail si oe newsteo! Chiar folosesc acelasi cont ca motor de smtp pentru vreo 60 de clienti! Never had this problem!

Poate ca acum s-a atins limita desi m-as mira pt ca in paralel am si newsteo pornit si de la ala primesc in draci mail si nu am fail de transmitere de loc in loguri!

So, the point is we must somehow find a way to configure how many emails get sent! O sa iti dau (nu pot acum) un print screen de la configurarea de la newsteo! 

Vorbim

**Comment by jeanleflambeur** [comment]
La email de retrigger, pus ultima valoare (cea mai recenta) de masuratoare pe fiecare senzor.

**Comment by jeanleflambeur** [comment]
Adaugat pre thresholds la alarme: temp & humidity

**Comment by jeanleflambeur** [comment]
1.0.16
