### ISSUE TITLE
Pana de curent => Base Station Disconnected => Manager.exe crash

### ISSUE THREAD

**Issue by Horhellito** [porkmarks/sense#97]
Tocmai am avut pana de curent.
Am constatat ca senzorii erau cu rosu, i.e. nu mai transmiteau si stocau in mem proprie.
Am intrat la Settings  BS si am vazut ca era "Basestation disconnected"
Am dat dublu click pe ea si a crashuit manager.exe la modu' ca s-a descarcat din memorie fara nici un mesaj.

Dupa ce am repornit aplicatia, aparent totul merge bine....
[data.zip](https://github.com/porkmarks/sense/files/2807439/data.zip)

**Comment by jeanleflambeur** [comment]
Ai UPS?
Banuiesc ca la pana de curent, BS-ul s-a restartat dar PC-ul nu?

**Comment by Horhellito** [comment]
Ideea era asa : Majoritatea clientilor nu vor avea UPS, si daca se intampla chestia asta, e o problema. Adica daca se intampla fara a fi avertizat clientul sau utilizatorul. 
PC-ul nu s-a restartat ca e laptop cu baterie...

Propunere 1:  daca mailul se trimite din manager.exe, atunci poate ca un ALERT TYPE nou gen : BASE STATION DISCONNECTED ar fi util (eventual cu un mesaj de genul sugestie ... "maybe you've just had a power failure" or such shit... 
Propunere 2:  Msgbox cu "Base Station Disconnected" pe ecran post pana de curent, dupa ce incearca de cateva ori si nu se poate conecta cu BS. Alegerea ta sau daca poti configurabil numar de retries pana la mesaj de eroare...

**Comment by jeanleflambeur** [comment]
1.0.16
