### ISSUE TITLE
Afisare alerte (problema si culori si subiectul EMAILULUI in functie de alerta sau revenire)

### ISSUE THREAD

**Issue by Horhellito** [porkmarks/sense#98]
Inca nu am studiat aprofundat alertele, dar exista trei probleme 

1. Vorbisem noi mai de mult ca alarmele transmit email de continand toti parametri senzorului de la momentul alarmei (temperature, humidity, battery, signal), insa cel care a triggeruit alarma o sa fie colorat altfel pentru a il distinge clar. Am observat ca unele sunt colorate acum si chiar (la alarmele de revenire sunt de alta culoare decat valorile anormale de la trigger-uirea alarmei. Dar nu toate. Vezi exemplul din captura de mai jos pe care o folosesc ca exemplu si pentru problema 2. Toate sunt negre, toate sunt valori normale, nu e nici una "back to normal" si totusi am primit email .... for no apparent reason :) 

2. In alarma de mai jos :  
Sensor 'home1' triggered alarm 'Temp Too High Home1 '.
Measurement:
•	Temperature: 21.9 °C normal
•	Humidity: 36.9 %RH normal
•	Battery: 63 % normal
•	Signal: Normal normal
este clar ca senzorul HOME 1 a pornit alarma TEMP TOO HIGH HOME 1 pentru ca temperatura a fost MAI MARE decat valoarea setata de mine pt aceasta alarma (vezi captura mai jos)
Pe de alta parte toate valorile sunt negre si mai si scrie NORMAL in dreapta lor (deci nu e alarma de out of range, nici de back to normal....dar e mail....
![image](https://user-images.githubusercontent.com/27699424/51920968-2071de00-23ef-11e9-9216-e1abd8770adb.png)

3. Emailurile au subiectele urmatoare (in functie de email) 
a. Trigger alert : Sensor 'c1', alarm 'Low Humidity All Sensors': 
b. Back to normal notification : Sensor 'c1', alarm 'Low Humidity All Sensors': Humidity back to normal

Pls modifica structura subiectelor astfel  : 
Pentru a. **ALARM** - Sensor 'c1', triggered alarm 'Low Humidity All Sensors': 
Pentru b. **BACK TO NORMAL** - Sensor 'c1', triggered recovery from alarm 'Low Humidity All Sensors':

**Comment by jeanleflambeur** [comment]
Legat de asta: 
Pentru a. ALARM - Sensor 'c1', triggered alarm 'Low Humidity All Sensors':
Pentru b. BACK TO NORMAL - Sensor 'c1', triggered recovery from alarm 'Low Humidity All Sensors':

Nu se pupa bine. Cand se trigereaza o alarma, sunt 3 stari:
1. Alarma nu era trigerata inainte, si a devenit activa
2. Alarma era activa si a devenit inactiva
3. Alarma era activa (de exemplu din cauza de humidity), si a ramas activa dar s-a schimbat triggerul (de exemplu humidity back to normal dar temp e triggered now)

Remember ca fiecare alarma poate avea X triggere independente: temp, hum, bat, signal

In fiecare caz de mai sus, subject va arata asa:
1. **Sensor 'XXX', alarm 'YYY': Triggered Temprature, Humidity**
2. **Sensor 'XXX', alarm 'YYY': Recovered Humidity, Battery**
3. **Sensor 'XXX', alarm 'YYY': Triggered Temprature, Humidity; Recovered Signal**

**Comment by jeanleflambeur** [comment]
Cum? In cazul 3 aceeasi alarma e si triggered si recovered.
Pot face asa:

1. Sensor 'XXX' Triggered alarm 'YYY': Temprature, Humidity
2. Sensor 'XXX' Recovered from alarm 'YYY': Humidity, Battery
3. Sensor 'XXX' Changed alarm 'YYY': Triggered Temprature, Humidity; Recovered Signal

**Comment by jeanleflambeur** [comment]
1.0.15
